key_left_once = keyboard_check_pressed(vk_left)
key_right_once = keyboard_check_pressed(vk_right)
key_up_once = keyboard_check_pressed(vk_up)
key_down_once = keyboard_check_pressed(vk_down)
key_left = keyboard_check(vk_left)
key_right = keyboard_check(vk_right)
key_up = keyboard_check(vk_up)
key_down = keyboard_check(vk_down)
key_a_once = keyboard_check_pressed(keyA)
key_b_once = keyboard_check_pressed(keyB)

if !surface_exists(arena_surface)
	arena_surface=surface_create(arena_width,arena_height)
surface_resize(arena_surface,arena_width+1,arena_height+1)
surface_set_target(arena_surface)
	draw_clear_alpha(c_white,0)
surface_reset_target()

event_user(1)